import { IChildren } from "@/Interface";

export const metadata = {
  title: "Connect Desk | Accounting Software",
  description: "Generated by Baitul Hikmah Team",
};

const AccountingSoftwareLayout = ({ children }: IChildren) => (
  <main>{children}</main>
);

export default AccountingSoftwareLayout;
