import { IChildren } from "@/Interface";

export const metadata = {
  title: "Connect Desk | Erp Software",
  description: "Generated by Baitul Hikmah Team",
};

const ErpSoftwareLayout = ({ children }: IChildren) => <main>{children}</main>;

export default ErpSoftwareLayout;
