import { IChildren } from "@/Interface";

export const metadata = {
  title: "Connect Desk | ECommerce Software",
  description: "Generated by Baitul Hikmah Team",
};

const ECommerceSoftwareLayout = ({ children }: IChildren) => (
  <main>{children}</main>
);

export default ECommerceSoftwareLayout;
