import { IChildren } from "@/Interface";

export const metadata = {
  title: "Connect Desk | Inventory Software",
  description: "Generated by Baitul Hikmah Team",
};

const InventorySoftwareLayout = ({ children }: IChildren) => (
  <main>{children}</main>
);

export default InventorySoftwareLayout;
