import { IChildren } from "@/Interface";

export const metadata = {
  title: "Connect Desk | HrPayroll Software",
  description: "Generated by Baitul Hikmah Team",
};

const HrPayrollSoftwareLayout = ({ children }: IChildren) => (
  <main>{children}</main>
);

export default HrPayrollSoftwareLayout;
