import { IChildren } from "@/Interface";

export const metadata = {
  title: "Connect Desk | Billing Software",
  description: "Generated by Baitul Hikmah Team",
};

const BillingSoftwareLayout = ({ children }: IChildren) => (
  <main>{children}</main>
);

export default BillingSoftwareLayout;
